---
title: "Welcome"
layout: post
date: "7/21/2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


My name is Taylor Reiter and I am graduate student at the University of California, Davis. My program is technically Food Science, but really I love food, biology, and bioinformatics. I have a lot of thoughts and opinions. I sometimes try and keep those to myself, but surely my opinions of science and bioinformatics will shine through in this blog. I'm a proponent of open science and so hither to and observe my trials and tribulations as I swim through entirely too much RNA-seq data and yet still make the argument for sequencing more!

Other things about me: I am member of the lab for Data Intensive Biology and the Olive Center analytical chemistry lab. I graduated from Harvard with a degree in Human Evolutionary Biology. I am still learning a lot, and recognize that I probably will make mistakes in this blog, but isn't that part of the adventure?

I consider my skills to include proficiency in R and bash, and wrangling RNA-seq data. I'm working on improving my python, git, and LaTeX. I often think of things evolutionarily, and I am working on my domain-specific biological knowledge in fruits (especially post-harvest) and soils.

Taylor Reiter  
4-19-17